spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native
  security:
    user:
      name: root
      password: root
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka